import { ISSUE_CODES, JURISDICTION_TABLE } from "@openpolicy/core";
import { Compliance } from "./compliance";
import { DataCategories, LegalBases, Retention } from "./data";
import { Providers } from "./providers";

/**
 * The PolicyStack **AI skill pack** (PS-32), generated from the same frozen
 * SDK/core tables as `llms.txt` (PS-27) so a skill can never reference a
 * removed `IssueCode`/jurisdiction — it rides the §6 freeze.
 *
 * One source of truth, shipped as a versioned **Claude Code plugin** in the
 * monorepo:
 *   - `renderSkillPack()` (this function) renders every plugin file; every
 *     enumeration is derived at call time from the live runtime tables the
 *     compiler and validator use (add a jurisdiction or an issue code and the
 *     skills update with it).
 *   - `scripts/gen-skills.mjs` snapshots the output to the repo-root `plugin/`
 *     tree after `vp pack`.
 *   - `skills.test.ts` guards the snapshot from drift, byte-for-byte.
 *
 * The four skills *compose existing primitives* — the shipped `@openpolicy/cli`
 * (`init`, `validate --json`), the `@openpolicy/react/provider`, and the
 * `@openpolicy/vite` scanner. They drive that surface; they do not reimplement
 * it. MCP (PS-29) is an optional tool a skill may prefer when present.
 *
 * `version` is pinned to the v1 line: PolicyStack 1.0 work carries no
 * changesets, so there is no automation to bump a root `plugin/` manifest.
 */
const PLUGIN_VERSION = "1.0.0";

const REPO = "https://github.com/jamiedavenport/openpolicy";

/** A single generated file, path relative to the repository root. */
export type SkillFile = { path: string; content: string };

const GENERATED_BANNER =
	"<!-- Generated by @openpolicy/sdk renderSkillPack() — do not edit by hand. Run `vp run gen:skills`. -->";

function jurisdictionRows(): string {
	// Same derivation/wording as renderLlmsTxt() so the drift canaries are
	// uniform across both artifacts.
	return Object.entries(JURISDICTION_TABLE)
		.sort(([a], [b]) => a.localeCompare(b))
		.map(([id, cap]) => {
			const parent = cap.parent ? `, inherits \`${cap.parent}\`` : "";
			const gpc = cap.gpcLegallyBinding ? ", GPC legally binding" : "";
			return `- \`${id}\` — ${cap.consentModel}, ${cap.policyText} policy text${parent}${gpc}`;
		})
		.join("\n");
}

function issueCodeRows(): string {
	return [...ISSUE_CODES]
		.sort((a, b) => a.code.localeCompare(b.code))
		.map((e) => `- \`${e.code}\` — *${e.level}* — ${e.summary}`)
		.join("\n");
}

function presetList(keys: string[], ns: string): string {
	return keys
		.sort()
		.map((k) => `\`${ns}.${k}\``)
		.join(", ");
}

function frontmatter(name: string, description: string): string {
	return `---\nname: ${name}\ndescription: ${description}\n---\n`;
}

function initSkill(): string {
	const jurisdictions = Object.keys(JURISDICTION_TABLE)
		.sort()
		.map((j) => `\`${j}\``)
		.join(", ");
	return `${frontmatter(
		"policystack-init",
		"Scaffold PolicyStack in a project: run the @openpolicy/cli installer, then wire <PolicyStackProvider> (policy + consent). Use when adding a privacy/cookie policy or a consent banner to a web app.",
	)}
${GENERATED_BANNER}

# policystack-init

Set PolicyStack up in an existing project. PolicyStack generates a privacy
policy, a cookie policy, and the consent runtime from **one** typed
\`defineConfig()\` call. It is not legal advice — a lawyer should review the
output before publication.

## 1. Run the installer

\`\`\`sh
npx @openpolicy/cli@latest init
\`\`\`

\`init\` detects the package manager and framework from \`package.json\`,
installs \`@openpolicy/sdk\` plus the right framework integration, scaffolds a
starter \`openpolicy.ts\` (\`src/openpolicy.ts\` when a \`src/\` directory
exists, else the project root), writes \`openpolicy.llms.txt\` next to it, and
prints a setup prompt. Useful flags: \`--cwd\`, \`--pm\`, \`--skip-install\`,
\`--dry-run\`, \`--yes\`, \`--out\`, \`--force\`.

If \`init\` cannot run, install by hand: \`@openpolicy/sdk\` always, plus
\`@openpolicy/vite\` and the framework package (\`@openpolicy/react\`, …).

## 2. Fill in \`openpolicy.ts\`

Read the generated \`openpolicy.llms.txt\` — it is the type-accurate SDK
reference (jurisdiction ids, lawful bases, presets) for this exact version.
The canonical, commented reference config is
[\`examples/tanstack/src/openpolicy.ts\`](${REPO}/blob/v1/examples/tanstack/src/openpolicy.ts).

\`jurisdictions\` is required and non-empty. Valid ids (frozen at 1.0):
${jurisdictions}. Any unlisted \`us-<state>\` falls back to \`us\`. Pick the
codes that actually apply; \`policystack-jurisdiction\` explains the posture
each implies.

## 3. Wire the provider

Wrap the app root **once** with the single provider — it supplies both the
policy context and the consent store (derived from the same config):

\`\`\`tsx
import { PolicyStackProvider } from "@openpolicy/react/provider";
import config from "./openpolicy";

export function App({ children }: { children: React.ReactNode }) {
	return <PolicyStackProvider config={config}>{children}</PolicyStackProvider>;
}
\`\`\`

\`<PrivacyPolicy>\` / \`<CookiePolicy>\`, \`useConsent\`, and \`ConsentGate\`
all read from it. Components ship unstyled and emit \`data-op-*\` attributes.
For non-React frameworks use that framework's \`@openpolicy/<fw>\` package.

## 4. Verify

Run \`policystack-audit\` (\`openpolicy validate --json\`) and resolve every
issue before shipping. Annotate real data flows with \`policystack-instrument\`
so the policy reflects what the code actually does.
`;
}

function auditSkill(): string {
	return `${frontmatter(
		"policystack-audit",
		"Audit an openpolicy.ts config: run `openpolicy validate --json`, explain each issue code, propose a minimal config fix, then re-validate until clean. Use when a PolicyStack config has validation errors or warnings.",
	)}
${GENERATED_BANNER}

# policystack-audit

Close the validate → explain → fix → re-validate loop on a PolicyStack config.

## 1. Validate

\`\`\`sh
npx @openpolicy/cli@latest validate --json
\`\`\`

\`--json\` writes exactly one object to stdout and nothing else:

\`\`\`ts
type ValidateResult = {
	ok: boolean; // false ⟺ exit code 1
	config: string; // resolved config path
	issues: { code: string; level: "error" | "warning"; message: string }[];
	errorCount: number;
	warningCount: number;
	loadError: string | null; // set instead of issues when the file won't load
};
\`\`\`

Branch on the exit code (or \`ok\`). \`loadError\` (missing file, TS syntax
error, no default export) is always \`ok: false\` and means **fix the load
error first** — there are no \`issues\` to triage yet. Pass a path or
\`--cwd\` if the config is not at the default location.

## 2. Explain each code

\`level\` is what \`validate()\` emits; the \`@openpolicy/vite\` plugin may
promote/suppress downstream, but errors block a valid config. Every code and
its durable meaning (the frozen 1.0 diagnostic surface — §6):

${issueCodeRows()}

## 3. Propose a minimal fix

For each issue, change only what the code requires in \`openpolicy.ts\` — do
not restyle or expand the config. \`error\`s must be resolved; \`warning\`s
should be resolved or consciously accepted (e.g. \`data-collected-empty\` is
correct for a brochure site). Never invent compliance facts (a lawful basis, a
DPO) — surface the decision to the user. Many data/cookie issues are better
fixed at the source with \`policystack-instrument\` than hand-written.

## 4. Re-validate

Re-run step 1. Repeat until \`ok: true\` (exit 0). Report the remaining
accepted warnings, if any.
`;
}

function jurisdictionSkill(): string {
	return `${frontmatter(
		"policystack-jurisdiction",
		"Explain the consent and policy-text posture (the §4.2 stance) implied by a set of declared PolicyStack `jurisdictions`. Use when choosing or reviewing the `jurisdictions` array in openpolicy.ts.",
	)}
${GENERATED_BANNER}

# policystack-jurisdiction

Explain what a declared \`jurisdictions\` set implies. Posture and policy-text
tier are read straight from the single canonical table (the same row the
policy renderer and the consent runtime read, so prose and banner always
agree). Membership is frozen at 1.0.

## The canonical table

${jurisdictionRows()}

## How to read it

- **consentModel** — \`opt-in\` (EEA/UK/CH/BR/CA/ROW): no non-essential
  data/cookies until affirmative consent; the banner defaults *off*.
  \`opt-out\` (US and US states): lawful by default after notice; the banner
  defaults *on*, gated by Do-Not-Sell / GPC.
- **policyText** — \`specific\` (\`eea\`, \`uk\`, \`us-ca\`): hand-authored,
  jurisdiction-specific prose. \`equivalent\`: posture-correct text via the
  \`parent\` jurisdiction — a legitimate, shippable tier that emits the
  \`jurisdiction-generic-policy-text\` **warning** so the gap is explicit, not
  silent. Treat that warning as acknowledged, not failed.
- **inherits** — US state codes inherit text/posture from \`us\`. Any
  \`us-<state>\` not in the table resolves to \`us\` (opt-out); \`row\` is the
  conservative opt-in catch-all. A code that is neither a table entry nor a
  \`us-*\` tail is rejected as \`jurisdiction-unknown\`.
- **GPC legally binding** — true only where the Global Privacy Control signal
  carries legal force (the §4.2 US-state set). It is always honoured as a
  signal regardless.

## Procedure

For each declared id: state its consent model, its policy-text tier (and the
parent it borrows from when \`equivalent\`), and whether GPC is binding. Call
out every \`equivalent\` id as a \`jurisdiction-generic-policy-text\` warning
the user must accept. The effective posture across a multi-jurisdiction set is
the **most protective** (any \`opt-in\` member ⇒ treat as opt-in).
`;
}

function instrumentSkill(): string {
	return `${frontmatter(
		"policystack-instrument",
		"Find un-annotated data collection and data egress in a codebase and add PolicyStack `collecting()` / `sharing()` / `thirdParty()` / `defineCookie()` call sites so the generated policy reflects what the code actually does.",
	)}
${GENERATED_BANNER}

# policystack-instrument

Make the policy reflect reality: annotate real data flows at their call sites
so the \`@openpolicy/vite\` build scans them into the config. The markers are
identity functions — they return their value unchanged and have **no runtime
effect**; the build reads them statically.

## The markers (from \`@openpolicy/sdk\`)

- \`collecting(category, value, labels)\` — wrap a value at the point it is
  stored. \`labels\` maps each field to a human label, or \`Ignore\` to
  exclude it (e.g. \`password: Ignore\`).
- \`sharing(key, recipient, value)\` — wrap an outbound payload at a data
  egress edge (the CCPA sell/share signal).
- \`thirdParty(name, purpose, policyUrl?)\` — declare a vendor exists; place
  next to its initialisation.
- \`defineCookie(category)\` — declare a consent category at its use site.

**Constraint:** \`category\`, \`key\`, \`recipient\`, \`name\` and the label
map must be **string / object literals**. Non-literal arguments are skipped by
the static scanner (it emits a build diagnostic — they are not silently lost,
but no annotation is produced). Never pass a variable.

## What counts as an un-annotated flow

The scanner already recognises common cookie/vendor surfaces (\`document.cookie\`,
\`js-cookie\`, \`cookies-next\`, \`react-cookie\`, server \`set-cookie\`, and
~30 known vendor imports) and flags any that are **not** gated by
\`<ConsentGate>\`, a \`consent.has(...)\` check, or an accept/set helper. Look
for, in priority order:

1. Persisted user input / DB writes with no nearby \`collecting()\`.
2. Outbound requests carrying user data (analytics, CRM, webhooks) with no
   \`sharing()\` and no \`thirdParty()\`.
3. Cookie / \`localStorage\` writes and tracker \`<script>\`/SDK init with no
   \`defineCookie()\` and not consent-gated.

## Procedure

1. Grep the data layer and network calls; list candidate flows.
2. Add the smallest correct marker at each call site, reusing presets where
   they fit so labels stay consistent:
   - Data categories: ${presetList(Object.keys(DataCategories), "DataCategories")}
   - Lawful bases: ${presetList(Object.keys(LegalBases), "LegalBases")}
   - Retention: ${presetList(Object.keys(Retention), "Retention")}
   - Vendors: ${presetList(Object.keys(Providers), "Providers")}
   - Compliance bundles: ${presetList(Object.keys(Compliance), "Compliance")}
3. Ensure every newly scanned category has a matching \`data.context\` /
   \`cookies.context\` entry in \`openpolicy.ts\` (the typed config enforces
   this).
4. Run \`policystack-audit\` to confirm the config still validates.
`;
}

function pluginManifest(): string {
	return `${JSON.stringify(
		{
			name: "policystack",
			version: PLUGIN_VERSION,
			description:
				"PolicyStack AI skill pack — scaffold, audit, jurisdiction posture, and data-flow instrumentation for privacy-first apps. Resolves against the frozen 1.0 SDK surface.",
			author: { name: "PolicyStack", url: REPO },
			homepage: `${REPO}#readme`,
			license: "Apache-2.0",
		},
		null,
		2,
	)}\n`;
}

function marketplaceManifest(): string {
	return `${JSON.stringify(
		{
			name: "policystack",
			owner: { name: "PolicyStack", url: REPO },
			plugins: [
				{
					name: "policystack",
					source: "./plugin",
					description:
						"PolicyStack AI skill pack: policystack-init, policystack-audit, policystack-jurisdiction, policystack-instrument.",
				},
			],
		},
		null,
		2,
	)}\n`;
}

/**
 * Render every file of the skill-pack plugin. Paths are relative to the
 * repository root; deterministic and sorted so the snapshot is stable.
 */
export function renderSkillPack(): SkillFile[] {
	return [
		{ path: ".claude-plugin/marketplace.json", content: marketplaceManifest() },
		{ path: "plugin/.claude-plugin/plugin.json", content: pluginManifest() },
		{ path: "plugin/skills/policystack-audit/SKILL.md", content: auditSkill() },
		{ path: "plugin/skills/policystack-init/SKILL.md", content: initSkill() },
		{
			path: "plugin/skills/policystack-instrument/SKILL.md",
			content: instrumentSkill(),
		},
		{
			path: "plugin/skills/policystack-jurisdiction/SKILL.md",
			content: jurisdictionSkill(),
		},
	];
}
