// AUTO-GENERATED by @policystack/vite — do not edit. (scan: 66861eea20c06b94)
import type { ScannedCollectionKeys } from "@policystack/sdk";

export const dataCollected: Record<keyof ScannedCollectionKeys & string, string[]> = {
	"Account Information": [
		"Name",
		"Email",
	],
	"Usage Data": [
		"Pages visited",
		"Browser type",
	],
};
export const thirdParties: { name: string; purpose: string; policyUrl: string }[] = [
	{
		"name": "Stripe",
		"purpose": "Payment processing",
		"policyUrl": "https://stripe.com/privacy",
	},
];
export const cookies: { essential: true; [key: string]: boolean } = {
	"essential": true,
};
export const sharing: { key: string; recipient: string }[] = [
	{
		"key": "Account Information",
		"recipient": "Stripe",
	},
];

declare module "@policystack/sdk" {
	interface ScannedCollectionKeys {
		"Account Information": true;
		"Usage Data": true;
	}
	interface ScannedCookieKeys {
		essential: true;
	}
	interface ScannedSharingKeys {
		"Account Information": true;
	}
}
