/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TailwindRouteImport } from './routes/tailwind'
import { Route as ShadcnRouteImport } from './routes/shadcn'
import { Route as OnboardingWizardRouteImport } from './routes/onboarding-wizard'
import { Route as NlRouteImport } from './routes/nl'
import { Route as FrRouteImport } from './routes/fr'
import { Route as EsRouteImport } from './routes/es'
import { Route as DeRouteImport } from './routes/de'
import { Route as CssVarsRouteImport } from './routes/css-vars'
import { Route as IndexRouteImport } from './routes/index'

const TailwindRoute = TailwindRouteImport.update({
  id: '/tailwind',
  path: '/tailwind',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadcnRoute = ShadcnRouteImport.update({
  id: '/shadcn',
  path: '/shadcn',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWizardRoute = OnboardingWizardRouteImport.update({
  id: '/onboarding-wizard',
  path: '/onboarding-wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const NlRoute = NlRouteImport.update({
  id: '/nl',
  path: '/nl',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const DeRoute = DeRouteImport.update({
  id: '/de',
  path: '/de',
  getParentRoute: () => rootRouteImport,
} as any)
const CssVarsRoute = CssVarsRouteImport.update({
  id: '/css-vars',
  path: '/css-vars',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/css-vars': typeof CssVarsRoute
  '/de': typeof DeRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/nl': typeof NlRoute
  '/onboarding-wizard': typeof OnboardingWizardRoute
  '/shadcn': typeof ShadcnRoute
  '/tailwind': typeof TailwindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/css-vars': typeof CssVarsRoute
  '/de': typeof DeRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/nl': typeof NlRoute
  '/onboarding-wizard': typeof OnboardingWizardRoute
  '/shadcn': typeof ShadcnRoute
  '/tailwind': typeof TailwindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/css-vars': typeof CssVarsRoute
  '/de': typeof DeRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/nl': typeof NlRoute
  '/onboarding-wizard': typeof OnboardingWizardRoute
  '/shadcn': typeof ShadcnRoute
  '/tailwind': typeof TailwindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/css-vars'
    | '/de'
    | '/es'
    | '/fr'
    | '/nl'
    | '/onboarding-wizard'
    | '/shadcn'
    | '/tailwind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/css-vars'
    | '/de'
    | '/es'
    | '/fr'
    | '/nl'
    | '/onboarding-wizard'
    | '/shadcn'
    | '/tailwind'
  id:
    | '__root__'
    | '/'
    | '/css-vars'
    | '/de'
    | '/es'
    | '/fr'
    | '/nl'
    | '/onboarding-wizard'
    | '/shadcn'
    | '/tailwind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CssVarsRoute: typeof CssVarsRoute
  DeRoute: typeof DeRoute
  EsRoute: typeof EsRoute
  FrRoute: typeof FrRoute
  NlRoute: typeof NlRoute
  OnboardingWizardRoute: typeof OnboardingWizardRoute
  ShadcnRoute: typeof ShadcnRoute
  TailwindRoute: typeof TailwindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tailwind': {
      id: '/tailwind'
      path: '/tailwind'
      fullPath: '/tailwind'
      preLoaderRoute: typeof TailwindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadcn': {
      id: '/shadcn'
      path: '/shadcn'
      fullPath: '/shadcn'
      preLoaderRoute: typeof ShadcnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-wizard': {
      id: '/onboarding-wizard'
      path: '/onboarding-wizard'
      fullPath: '/onboarding-wizard'
      preLoaderRoute: typeof OnboardingWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nl': {
      id: '/nl'
      path: '/nl'
      fullPath: '/nl'
      preLoaderRoute: typeof NlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de': {
      id: '/de'
      path: '/de'
      fullPath: '/de'
      preLoaderRoute: typeof DeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-vars': {
      id: '/css-vars'
      path: '/css-vars'
      fullPath: '/css-vars'
      preLoaderRoute: typeof CssVarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CssVarsRoute: CssVarsRoute,
  DeRoute: DeRoute,
  EsRoute: EsRoute,
  FrRoute: FrRoute,
  NlRoute: NlRoute,
  OnboardingWizardRoute: OnboardingWizardRoute,
  ShadcnRoute: ShadcnRoute,
  TailwindRoute: TailwindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
