/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SdkDottxtRouteImport } from './routes/sdk[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PolicyDotmdRouteImport } from './routes/policy[.]md'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as IndexDotmdRouteImport } from './routes/index[.]md'
import { Route as DocsDotmdRouteImport } from './routes/docs[.]md'
import { Route as ConsentDotmdRouteImport } from './routes/consent[.]md'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as CloudDotmdRouteImport } from './routes/cloud[.]md'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as BlogDotmdRouteImport } from './routes/blog[.]md'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as OgSplatRouteImport } from './routes/og/$'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'

const SdkDottxtRoute = SdkDottxtRouteImport.update({
  id: '/sdk.txt',
  path: '/sdk.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyDotmdRoute = PolicyDotmdRouteImport.update({
  id: '/policy.md',
  path: '/policy.md',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDotmdRoute = IndexDotmdRouteImport.update({
  id: '/index.md',
  path: '/index.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDotmdRoute = DocsDotmdRouteImport.update({
  id: '/docs.md',
  path: '/docs.md',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentDotmdRoute = ConsentDotmdRouteImport.update({
  id: '/consent.md',
  path: '/consent.md',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudDotmdRoute = CloudDotmdRouteImport.update({
  id: '/cloud.md',
  path: '/cloud.md',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogDotmdRoute = BlogDotmdRouteImport.update({
  id: '/blog.md',
  path: '/blog.md',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const OgSplatRoute = OgSplatRouteImport.update({
  id: '/og/$',
  path: '/og/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/blog': typeof BlogRoute
  '/blog.md': typeof BlogDotmdRoute
  '/cloud': typeof CloudRoute
  '/cloud.md': typeof CloudDotmdRoute
  '/consent': typeof ConsentRoute
  '/consent.md': typeof ConsentDotmdRoute
  '/docs.md': typeof DocsDotmdRoute
  '/index.md': typeof IndexDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/policy': typeof PolicyRoute
  '/policy.md': typeof PolicyDotmdRoute
  '/privacy': typeof PrivacyRoute
  '/sdk.txt': typeof SdkDottxtRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/og/$': typeof OgSplatRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/blog.md': typeof BlogDotmdRoute
  '/cloud': typeof CloudRoute
  '/cloud.md': typeof CloudDotmdRoute
  '/consent': typeof ConsentRoute
  '/consent.md': typeof ConsentDotmdRoute
  '/docs.md': typeof DocsDotmdRoute
  '/index.md': typeof IndexDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/policy': typeof PolicyRoute
  '/policy.md': typeof PolicyDotmdRoute
  '/privacy': typeof PrivacyRoute
  '/sdk.txt': typeof SdkDottxtRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/og/$': typeof OgSplatRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/blog': typeof BlogRoute
  '/blog.md': typeof BlogDotmdRoute
  '/cloud': typeof CloudRoute
  '/cloud.md': typeof CloudDotmdRoute
  '/consent': typeof ConsentRoute
  '/consent.md': typeof ConsentDotmdRoute
  '/docs.md': typeof DocsDotmdRoute
  '/index.md': typeof IndexDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/policy': typeof PolicyRoute
  '/policy.md': typeof PolicyDotmdRoute
  '/privacy': typeof PrivacyRoute
  '/sdk.txt': typeof SdkDottxtRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/og/$': typeof OgSplatRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/blog'
    | '/blog.md'
    | '/cloud'
    | '/cloud.md'
    | '/consent'
    | '/consent.md'
    | '/docs.md'
    | '/index.md'
    | '/llms.txt'
    | '/policy'
    | '/policy.md'
    | '/privacy'
    | '/sdk.txt'
    | '/blog/$slug'
    | '/docs/$'
    | '/og/$'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/blog.md'
    | '/cloud'
    | '/cloud.md'
    | '/consent'
    | '/consent.md'
    | '/docs.md'
    | '/index.md'
    | '/llms.txt'
    | '/policy'
    | '/policy.md'
    | '/privacy'
    | '/sdk.txt'
    | '/blog/$slug'
    | '/docs/$'
    | '/og/$'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/blog'
    | '/blog.md'
    | '/cloud'
    | '/cloud.md'
    | '/consent'
    | '/consent.md'
    | '/docs.md'
    | '/index.md'
    | '/llms.txt'
    | '/policy'
    | '/policy.md'
    | '/privacy'
    | '/sdk.txt'
    | '/blog_/$slug'
    | '/docs/$'
    | '/og/$'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  BlogRoute: typeof BlogRoute
  BlogDotmdRoute: typeof BlogDotmdRoute
  CloudRoute: typeof CloudRoute
  CloudDotmdRoute: typeof CloudDotmdRoute
  ConsentRoute: typeof ConsentRoute
  ConsentDotmdRoute: typeof ConsentDotmdRoute
  DocsDotmdRoute: typeof DocsDotmdRoute
  IndexDotmdRoute: typeof IndexDotmdRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PolicyRoute: typeof PolicyRoute
  PolicyDotmdRoute: typeof PolicyDotmdRoute
  PrivacyRoute: typeof PrivacyRoute
  SdkDottxtRoute: typeof SdkDottxtRoute
  BlogSlugRoute: typeof BlogSlugRoute
  OgSplatRoute: typeof OgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sdk.txt': {
      id: '/sdk.txt'
      path: '/sdk.txt'
      fullPath: '/sdk.txt'
      preLoaderRoute: typeof SdkDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy.md': {
      id: '/policy.md'
      path: '/policy.md'
      fullPath: '/policy.md'
      preLoaderRoute: typeof PolicyDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index.md': {
      id: '/index.md'
      path: '/index.md'
      fullPath: '/index.md'
      preLoaderRoute: typeof IndexDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs.md': {
      id: '/docs.md'
      path: '/docs.md'
      fullPath: '/docs.md'
      preLoaderRoute: typeof DocsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent.md': {
      id: '/consent.md'
      path: '/consent.md'
      fullPath: '/consent.md'
      preLoaderRoute: typeof ConsentDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud.md': {
      id: '/cloud.md'
      path: '/cloud.md'
      fullPath: '/cloud.md'
      preLoaderRoute: typeof CloudDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog.md': {
      id: '/blog.md'
      path: '/blog.md'
      fullPath: '/blog.md'
      preLoaderRoute: typeof BlogDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/og/$': {
      id: '/og/$'
      path: '/og/$'
      fullPath: '/og/$'
      preLoaderRoute: typeof OgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  BlogRoute: BlogRoute,
  BlogDotmdRoute: BlogDotmdRoute,
  CloudRoute: CloudRoute,
  CloudDotmdRoute: CloudDotmdRoute,
  ConsentRoute: ConsentRoute,
  ConsentDotmdRoute: ConsentDotmdRoute,
  DocsDotmdRoute: DocsDotmdRoute,
  IndexDotmdRoute: IndexDotmdRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PolicyRoute: PolicyRoute,
  PolicyDotmdRoute: PolicyDotmdRoute,
  PrivacyRoute: PrivacyRoute,
  SdkDottxtRoute: SdkDottxtRoute,
  BlogSlugRoute: BlogSlugRoute,
  OgSplatRoute: OgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
