/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SdkDottxtRouteImport } from './routes/sdk[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PolicycloudDotmdRouteImport } from './routes/policycloud[.]md'
import { Route as PolicycloudRouteImport } from './routes/policycloud'
import { Route as OpenpolicyDotmdRouteImport } from './routes/openpolicy[.]md'
import { Route as OpenpolicyRouteImport } from './routes/openpolicy'
import { Route as OpencookiesDotmdRouteImport } from './routes/opencookies[.]md'
import { Route as OpencookiesRouteImport } from './routes/opencookies'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as IndexDotmdRouteImport } from './routes/index[.]md'
import { Route as DocsDotmdRouteImport } from './routes/docs[.]md'
import { Route as BlogDotmdRouteImport } from './routes/blog[.]md'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as OgSplatRouteImport } from './routes/og/$'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'

const SdkDottxtRoute = SdkDottxtRouteImport.update({
  id: '/sdk.txt',
  path: '/sdk.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicycloudDotmdRoute = PolicycloudDotmdRouteImport.update({
  id: '/policycloud.md',
  path: '/policycloud.md',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicycloudRoute = PolicycloudRouteImport.update({
  id: '/policycloud',
  path: '/policycloud',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenpolicyDotmdRoute = OpenpolicyDotmdRouteImport.update({
  id: '/openpolicy.md',
  path: '/openpolicy.md',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenpolicyRoute = OpenpolicyRouteImport.update({
  id: '/openpolicy',
  path: '/openpolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const OpencookiesDotmdRoute = OpencookiesDotmdRouteImport.update({
  id: '/opencookies.md',
  path: '/opencookies.md',
  getParentRoute: () => rootRouteImport,
} as any)
const OpencookiesRoute = OpencookiesRouteImport.update({
  id: '/opencookies',
  path: '/opencookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDotmdRoute = IndexDotmdRouteImport.update({
  id: '/index.md',
  path: '/index.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDotmdRoute = DocsDotmdRouteImport.update({
  id: '/docs.md',
  path: '/docs.md',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogDotmdRoute = BlogDotmdRouteImport.update({
  id: '/blog.md',
  path: '/blog.md',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const OgSplatRoute = OgSplatRouteImport.update({
  id: '/og/$',
  path: '/og/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/blog': typeof BlogRoute
  '/blog.md': typeof BlogDotmdRoute
  '/docs.md': typeof DocsDotmdRoute
  '/index.md': typeof IndexDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/opencookies': typeof OpencookiesRoute
  '/opencookies.md': typeof OpencookiesDotmdRoute
  '/openpolicy': typeof OpenpolicyRoute
  '/openpolicy.md': typeof OpenpolicyDotmdRoute
  '/policycloud': typeof PolicycloudRoute
  '/policycloud.md': typeof PolicycloudDotmdRoute
  '/privacy': typeof PrivacyRoute
  '/sdk.txt': typeof SdkDottxtRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/og/$': typeof OgSplatRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/blog.md': typeof BlogDotmdRoute
  '/docs.md': typeof DocsDotmdRoute
  '/index.md': typeof IndexDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/opencookies': typeof OpencookiesRoute
  '/opencookies.md': typeof OpencookiesDotmdRoute
  '/openpolicy': typeof OpenpolicyRoute
  '/openpolicy.md': typeof OpenpolicyDotmdRoute
  '/policycloud': typeof PolicycloudRoute
  '/policycloud.md': typeof PolicycloudDotmdRoute
  '/privacy': typeof PrivacyRoute
  '/sdk.txt': typeof SdkDottxtRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/og/$': typeof OgSplatRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/blog': typeof BlogRoute
  '/blog.md': typeof BlogDotmdRoute
  '/docs.md': typeof DocsDotmdRoute
  '/index.md': typeof IndexDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/opencookies': typeof OpencookiesRoute
  '/opencookies.md': typeof OpencookiesDotmdRoute
  '/openpolicy': typeof OpenpolicyRoute
  '/openpolicy.md': typeof OpenpolicyDotmdRoute
  '/policycloud': typeof PolicycloudRoute
  '/policycloud.md': typeof PolicycloudDotmdRoute
  '/privacy': typeof PrivacyRoute
  '/sdk.txt': typeof SdkDottxtRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/og/$': typeof OgSplatRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/blog'
    | '/blog.md'
    | '/docs.md'
    | '/index.md'
    | '/llms.txt'
    | '/opencookies'
    | '/opencookies.md'
    | '/openpolicy'
    | '/openpolicy.md'
    | '/policycloud'
    | '/policycloud.md'
    | '/privacy'
    | '/sdk.txt'
    | '/blog/$slug'
    | '/docs/$'
    | '/og/$'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/blog.md'
    | '/docs.md'
    | '/index.md'
    | '/llms.txt'
    | '/opencookies'
    | '/opencookies.md'
    | '/openpolicy'
    | '/openpolicy.md'
    | '/policycloud'
    | '/policycloud.md'
    | '/privacy'
    | '/sdk.txt'
    | '/blog/$slug'
    | '/docs/$'
    | '/og/$'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/blog'
    | '/blog.md'
    | '/docs.md'
    | '/index.md'
    | '/llms.txt'
    | '/opencookies'
    | '/opencookies.md'
    | '/openpolicy'
    | '/openpolicy.md'
    | '/policycloud'
    | '/policycloud.md'
    | '/privacy'
    | '/sdk.txt'
    | '/blog_/$slug'
    | '/docs/$'
    | '/og/$'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  BlogRoute: typeof BlogRoute
  BlogDotmdRoute: typeof BlogDotmdRoute
  DocsDotmdRoute: typeof DocsDotmdRoute
  IndexDotmdRoute: typeof IndexDotmdRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OpencookiesRoute: typeof OpencookiesRoute
  OpencookiesDotmdRoute: typeof OpencookiesDotmdRoute
  OpenpolicyRoute: typeof OpenpolicyRoute
  OpenpolicyDotmdRoute: typeof OpenpolicyDotmdRoute
  PolicycloudRoute: typeof PolicycloudRoute
  PolicycloudDotmdRoute: typeof PolicycloudDotmdRoute
  PrivacyRoute: typeof PrivacyRoute
  SdkDottxtRoute: typeof SdkDottxtRoute
  BlogSlugRoute: typeof BlogSlugRoute
  OgSplatRoute: typeof OgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sdk.txt': {
      id: '/sdk.txt'
      path: '/sdk.txt'
      fullPath: '/sdk.txt'
      preLoaderRoute: typeof SdkDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policycloud.md': {
      id: '/policycloud.md'
      path: '/policycloud.md'
      fullPath: '/policycloud.md'
      preLoaderRoute: typeof PolicycloudDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policycloud': {
      id: '/policycloud'
      path: '/policycloud'
      fullPath: '/policycloud'
      preLoaderRoute: typeof PolicycloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openpolicy.md': {
      id: '/openpolicy.md'
      path: '/openpolicy.md'
      fullPath: '/openpolicy.md'
      preLoaderRoute: typeof OpenpolicyDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openpolicy': {
      id: '/openpolicy'
      path: '/openpolicy'
      fullPath: '/openpolicy'
      preLoaderRoute: typeof OpenpolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opencookies.md': {
      id: '/opencookies.md'
      path: '/opencookies.md'
      fullPath: '/opencookies.md'
      preLoaderRoute: typeof OpencookiesDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opencookies': {
      id: '/opencookies'
      path: '/opencookies'
      fullPath: '/opencookies'
      preLoaderRoute: typeof OpencookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index.md': {
      id: '/index.md'
      path: '/index.md'
      fullPath: '/index.md'
      preLoaderRoute: typeof IndexDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs.md': {
      id: '/docs.md'
      path: '/docs.md'
      fullPath: '/docs.md'
      preLoaderRoute: typeof DocsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog.md': {
      id: '/blog.md'
      path: '/blog.md'
      fullPath: '/blog.md'
      preLoaderRoute: typeof BlogDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/og/$': {
      id: '/og/$'
      path: '/og/$'
      fullPath: '/og/$'
      preLoaderRoute: typeof OgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  BlogRoute: BlogRoute,
  BlogDotmdRoute: BlogDotmdRoute,
  DocsDotmdRoute: DocsDotmdRoute,
  IndexDotmdRoute: IndexDotmdRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OpencookiesRoute: OpencookiesRoute,
  OpencookiesDotmdRoute: OpencookiesDotmdRoute,
  OpenpolicyRoute: OpenpolicyRoute,
  OpenpolicyDotmdRoute: OpenpolicyDotmdRoute,
  PolicycloudRoute: PolicycloudRoute,
  PolicycloudDotmdRoute: PolicycloudDotmdRoute,
  PrivacyRoute: PrivacyRoute,
  SdkDottxtRoute: SdkDottxtRoute,
  BlogSlugRoute: BlogSlugRoute,
  OgSplatRoute: OgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
