import type { ThirdPartyEntry } from "./analyse";

export type CookieMap = { essential: boolean; [key: string]: boolean };

export type Scanned = {
	dataCollected: Record<string, string[]>;
	thirdParties: ThirdPartyEntry[];
	cookies: CookieMap;
};

/**
 * Renders the full source of the on-disk `openpolicy.gen.ts` module emitted
 * next to the user's `openpolicy.ts`. The module is imported explicitly by the
 * config and carries two things:
 *
 *  1. The scanned runtime values (`dataCollected` / `thirdParties` /
 *     `cookies`), annotated with the exact public types `@openpolicy/sdk`
 *     used to export so `defineConfig`'s generic inference is unchanged. The
 *     values are emitted as JSON, which is valid TypeScript.
 *  2. A `declare module "@openpolicy/sdk"` augmentation of
 *     `ScannedCollectionKeys` / `ScannedCookieKeys` so `defineConfig` requires
 *     a sibling `data.context` / `cookies.context` entry for every scanned
 *     key.
 *
 * The augmentation keys are sorted so the committed file is deterministic.
 * The file is excluded from formatting (`fmt.ignorePatterns`), so the compact
 * JSON values don't need to match the project's formatter.
 */
export function renderGenModule(scanned: Scanned): string {
	const dataAugment = Object.keys(scanned.dataCollected)
		.sort()
		.map((k) => `\t\t${JSON.stringify(k)}: true;`)
		.join("\n");
	const cookieAugment = Object.keys(scanned.cookies)
		.sort()
		.map((k) => `\t\t${JSON.stringify(k)}: true;`)
		.join("\n");

	return (
		`// AUTO-GENERATED by @openpolicy/vite — do not edit.\n` +
		`import type { ScannedCollectionKeys } from "@openpolicy/sdk";\n` +
		`\n` +
		`export const dataCollected: Record<keyof ScannedCollectionKeys & string, string[]> = ${JSON.stringify(
			scanned.dataCollected,
		)};\n` +
		`export const thirdParties: { name: string; purpose: string; policyUrl: string }[] = ${JSON.stringify(
			scanned.thirdParties,
		)};\n` +
		`export const cookies: { essential: true; [key: string]: boolean } = ${JSON.stringify(
			scanned.cookies,
		)};\n` +
		`\n` +
		`declare module "@openpolicy/sdk" {\n` +
		`\tinterface ScannedCollectionKeys {\n` +
		(dataAugment ? `${dataAugment}\n` : "") +
		`\t}\n` +
		`\tinterface ScannedCookieKeys {\n` +
		(cookieAugment ? `${cookieAugment}\n` : "") +
		`\t}\n` +
		`}\n`
	);
}
