import { expect, test } from "vite-plus/test";
import { genDigest, readGenDigest, renderGenModule, type Scanned } from "./scanned";

function scanned(overrides: Partial<Scanned> = {}): Scanned {
	return {
		dataCollected: {},
		thirdParties: [],
		cookies: { essential: true },
		sharing: [],
		diagnostics: [],
		...overrides,
	};
}

test("renderGenModule stamps the scan digest into the header comment", () => {
	const input = scanned({ dataCollected: { "Account Information": ["Email"] } });
	const firstLine = renderGenModule(input).split("\n")[0] as string;
	expect(firstLine).toBe(
		`// AUTO-GENERATED by @policystack/vite — do not edit. (scan: ${genDigest(input)})`,
	);
	expect(readGenDigest(renderGenModule(input))).toBe(genDigest(input));
});

test("renderGenModule pretty-prints values one entry per line", () => {
	const source = renderGenModule(
		scanned({
			dataCollected: { "Account Information": ["Email", "Name"] },
			cookies: { essential: true, analytics: true },
		}),
	);
	expect(source).toContain(
		`export const dataCollected: Record<keyof ScannedCollectionKeys & string, string[]> = {\n` +
			`\t"Account Information": [\n` +
			`\t\t"Email",\n` +
			`\t\t"Name",\n` +
			`\t],\n` +
			`};\n`,
	);
	expect(source).toContain(
		`export const cookies: { essential: true; [key: string]: boolean } = {\n` +
			`\t"essential": true,\n` +
			`\t"analytics": true,\n` +
			`};\n`,
	);
	// No compact `JSON.stringify` output survives anywhere.
	expect(source).not.toContain('":[');
	expect(source).not.toContain('":{');
});

test("renderGenModule collapses empty values and empty augmentations to one line", () => {
	const source = renderGenModule(scanned());
	expect(source).toContain(
		"export const dataCollected: Record<keyof ScannedCollectionKeys & string, string[]> = {};",
	);
	expect(source).toContain(
		"export const thirdParties: { name: string; purpose: string; policyUrl: string }[] = [];",
	);
	expect(source).toContain("\tinterface ScannedCollectionKeys {}\n");
	expect(source).toContain("\tinterface ScannedSharingKeys {}\n");
});

test("renderGenModule quotes augmentation keys only where an identifier won't do", () => {
	const source = renderGenModule(
		scanned({
			dataCollected: { "Account Information": ["Email"], sessionData: ["IP"] },
		}),
	);
	expect(source).toContain(
		`\tinterface ScannedCollectionKeys {\n` +
			`\t\t"Account Information": true;\n` +
			`\t\tsessionData: true;\n` +
			`\t}\n`,
	);
	// Values keep their quotes regardless, so each literal stays JSON.
	expect(source).toContain(`\t"sessionData": [\n`);
});

test("renderGenModule sorts and dedupes augmentation keys", () => {
	const source = renderGenModule(
		scanned({
			sharing: [
				{ key: "Usage Data", recipient: "Stripe" },
				{ key: "Account Information", recipient: "Stripe" },
				{ key: "Account Information", recipient: "Segment" },
			],
		}),
	);
	expect(source).toContain(
		`\tinterface ScannedSharingKeys {\n` +
			`\t\t"Account Information": true;\n` +
			`\t\t"Usage Data": true;\n` +
			`\t}\n`,
	);
});

test("genDigest ignores ordering so a reordered scan is not a content change", () => {
	const a = scanned({
		dataCollected: { Billing: ["Card"], Account: ["Email"] },
		cookies: { essential: true, analytics: true },
		thirdParties: [
			{ name: "Stripe", purpose: "Payments", policyUrl: "https://stripe.com/privacy" },
			{ name: "Segment", purpose: "Analytics", policyUrl: "https://segment.com/privacy" },
		],
	});
	const b = scanned({
		dataCollected: { Account: ["Email"], Billing: ["Card"] },
		cookies: { analytics: true, essential: true },
		thirdParties: [
			{ name: "Segment", purpose: "Analytics", policyUrl: "https://segment.com/privacy" },
			{ name: "Stripe", purpose: "Payments", policyUrl: "https://stripe.com/privacy" },
		],
	});
	expect(genDigest(a)).toBe(genDigest(b));
});

test("genDigest ignores diagnostics, which never reach the module", () => {
	const base = scanned({ dataCollected: { Account: ["Email"] } });
	const withDiagnostic = scanned({
		dataCollected: { Account: ["Email"] },
		diagnostics: [
			{
				code: "non-literal-argument",
				message: "skipped",
				file: "src/a.ts",
				line: 1,
				column: 1,
			},
		],
	});
	expect(genDigest(withDiagnostic)).toBe(genDigest(base));
});

test("genDigest changes when any rendered value changes", () => {
	const base = scanned({ dataCollected: { Account: ["Email"] } });
	expect(genDigest(scanned({ dataCollected: { Account: ["Email", "Name"] } }))).not.toBe(
		genDigest(base),
	);
	expect(genDigest(scanned({ dataCollected: { Billing: ["Email"] } }))).not.toBe(genDigest(base));
	expect(
		genDigest(
			scanned({
				dataCollected: { Account: ["Email"] },
				cookies: { essential: true, analytics: true },
			}),
		),
	).not.toBe(genDigest(base));
});

test("readGenDigest survives a consumer reformatting the file", () => {
	const source = renderGenModule(scanned({ dataCollected: { Account: ["Email"] } }));
	const formatted = `${source.replace(/\t/g, "  ").replace(/"/g, "'")}\n`;
	expect(readGenDigest(formatted)).toBe(
		genDigest(scanned({ dataCollected: { Account: ["Email"] } })),
	);
});

test("readGenDigest returns null for a header without a digest", () => {
	expect(readGenDigest("// AUTO-GENERATED by @policystack/vite — do not edit.\nexport {};\n")).toBe(
		null,
	);
	expect(readGenDigest("")).toBe(null);
	expect(readGenDigest("export const dataCollected = {};\n")).toBe(null);
});
